// const prod_url: string = 'http://rsmgmt.ivisecurity.com';
const prod_url: string = 'http://prod.ivisecurity.com';

export const environment = {
  production: true,

  authUrl: `${prod_url}:3002`,
  commonDownUrl: `${prod_url}:3001`,
  metadataUrl: `${prod_url}:3005`,
  sitesUrl: `${prod_url}:3004`,
  incidentsUrl: `${prod_url}:8945`,
  helpdeskUrl: `${prod_url}:3003`,
  insightsUrl: `${prod_url}:3006`,
  timelapseUrl: `${prod_url}:3010`,
  adsUrl: `${prod_url}:8946`,
  sensorUrl: `${prod_url}:3011`,
  simsUrl:`${prod_url}:3012`,
  faqUrl: `${prod_url}:3008`,

  // authUrl: `${prod_url}/userDetails`,
  // sitesUrl: `${prod_url}/vipsites`,
  // metadataUrl: `${prod_url}/metadata`,
  // commonDownUrl: `${prod_url}/common`,
  // adsUrl: `${prod_url}/proximityAdsMain`,
  // rulesUrl: `${prod_url}/proximityAdsRules `,
  // insightsUrl: `${prod_url}/insights`,
  // timelapseUrl: `${prod_url}/timeLapse`,
  // sensorUrl:`${prod_url}/sensors`,
  // simsUrl:`${prod_url}/simDevices`,
  // faqUrl: `${prod_url}/faq`,
  // inventoryUrl: `${prod_url}/inventory`,
  // helpdeskUrl: `${prod_url}/supportRequests`,
  // incidentsUrl: `${prod_url}/guard_monitoring`,

  // authUrl: `https://authivis-rsmgmt.ivisecurity.com/userDetails`,
  // metadataUrl: `https://metadata-rsmgmt.ivisecurity.com/metadata`,
  // commonDownUrl: `https://common-s3-rsmgmt.ivisecurity.com/common`,
  // sitesUrl: `https://vipsites-rsmgmt.ivisecurity.com/vipsites`,
  // incidentsUrl: `https://alerts-rsmgmt.ivisecurity.com/incidents`,
  // sensorUrl: `https://iot-rsmgmt.ivisecurity.com/sensors`,
  // simsUrl:`https://sim-rsmgmt.ivisecurity.com/simDevices/simDevices`,
  // helpdeskUrl: `https://sup-rsmgmt.ivisecurity.com/supportRequests`,
  // insightsUrl: `https://bi-rsmgmt.ivisecurity.com/insights`,
  // adsUrl: `https://prox-rsmgmt.ivisecurity.com/proximityAdsMain`,
  // timelapseUrl: `https://timelapse-rsmgmt.ivisecurity.com/timeLapse`,
};
