// const dev_url: string = 'http://rsmgmt.ivisecurity.com';
const prod_url: string = 'https://prod.ivisecurity.com';

export const environment = {
  production: true,

  // authUrl: `${dev_url}/userDetails`,
  // sitesUrl: `${dev_url}/vipsites`,
  // metadataUrl: `${dev_url}/metadata`,
  // commonDownUrl: `${dev_url}/common`,
  // adsUrl: `${dev_url}/proximityAdsMain`,
  // rulesUrl: `${dev_url}/proximityAdsRules `,
  // insightsUrl: `${dev_url}/insights`,
  // timelapseUrl: `${dev_url}/timeLapse`,
  // sensorUrl:`${dev_url}/sensors`,
  // simsUrl:`${dev_url}/simDevices`,
  // faqUrl: `${dev_url}/faq`,
  // inventoryUrl: `${dev_url}/inventory`,
  // helpdeskUrl: `${dev_url}/supportRequests`,
  // incidentsUrl: `${dev_url}/guard_monitoring`,

  authUrl: `${prod_url}/userDetails`,
  sitesUrl: `${prod_url}/vipsites`,
  metadataUrl: `${prod_url}/metadata`,
  commonDownUrl: `${prod_url}/common`,
  adsUrl: `${prod_url}/proximityAdsMain`,
  rulesUrl: `${prod_url}/proximityAdsRules `,
  insightsUrl: `${prod_url}/insights`,
  timelapseUrl: `${prod_url}/timeLapse`,
  sensorUrl:`${prod_url}/sensors`,
  simsUrl:`${prod_url}/simDevices`,
  faqUrl: `${prod_url}/faq`,
  inventoryUrl: `${prod_url}/inventory`,
  helpdeskUrl: `${prod_url}/supportRequests`,
  incidentsUrl: `${prod_url}/guard_monitoring`,

  // authUrl: `https://authivis-rsmgmt.ivisecurity.com/userDetails`,
  // metadataUrl: `https://metadata-rsmgmt.ivisecurity.com/metadata`,
  // commonDownUrl: `https://common-s3-rsmgmt.ivisecurity.com/common`,
  // sitesUrl: `https://vipsites-rsmgmt.ivisecurity.com/vipsites`,
  // incidentsUrl: `https://alerts-rsmgmt.ivisecurity.com/incidents`,
  // sensorUrl: `https://iot-rsmgmt.ivisecurity.com/sensors`,
  // simsUrl:`https://sim-rsmgmt.ivisecurity.com/simDevices/simDevices`,
  // helpdeskUrl: `https://sup-rsmgmt.ivisecurity.com/supportRequests`,
  // insightsUrl: `https://bi-rsmgmt.ivisecurity.com/insights`,
  // adsUrl: `https://prox-rsmgmt.ivisecurity.com/proximityAdsMain`,
  // timelapseUrl: `https://timelapse-rsmgmt.ivisecurity.com/timeLapse`,
};
